name: WolfWhisper
options:
  bundleIdPrefix: com.wolfwhisper
  deploymentTarget:
    macOS: "14.0"

dependencies: [
    # Removed Atomics package
]

targets:
  WolfWhisper:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - WolfWhisper
    resources:
      - WolfWhisper/Assets.xcassets
      - WolfWhisper/Info.plist
    info:
      path: WolfWhisper/Info.plist
      properties:
        NSMicrophoneUsageDescription: "WolfWhisper needs microphone access to record your voice for dictation."
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.wolfwhisper.app
      PRODUCT_NAME: WolfWhisper
      PRODUCT_MODULE_NAME: WolfWhisper
      SWIFT_VERSION: 6.0
      GENERATE_INFOPLIST_FILE: NO
      INFOPLIST_FILE: WolfWhisper/Info.plist
    dependencies: [
                 # Removed Atomics product
             ] 